# Generated by Django 3.2.14 on 2022-11-14 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('username', models.CharField(max_length=20, verbose_name='Usuario')),
                ('email', models.EmailField(max_length=150, verbose_name='email')),
                ('password', models.CharField(max_length=20, verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrep', models.CharField(max_length=50, verbose_name='NombreP')),
                ('imagenp', models.ImageField(upload_to='#', verbose_name='ImagenP')),
                ('website', models.URLField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cac.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Posteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo')),
                ('resumen', models.CharField(max_length=250, verbose_name='Resumen')),
                ('articulo', models.TextField(verbose_name='Articulo')),
                ('imagenpos', models.ImageField(upload_to='#', verbose_name='ImagenPos')),
                ('fecha', models.DateField(auto_now=True, verbose_name='Fecha')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cac.categoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cac.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrec', models.CharField(max_length=50, verbose_name='NombreC')),
                ('comentarios', models.CharField(max_length=250, verbose_name='Comentarios')),
                ('email', models.EmailField(max_length=150, verbose_name='email')),
                ('fechac', models.DateField(auto_now=True, verbose_name='FechaC')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cac.posteo')),
            ],
        ),
    ]
