# Generated by Django 3.2.14 on 2022-12-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cac', '0003_auto_20221124_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
    ]
